algo_name: 'sac'
seed: 10
env_name: 'reaching-v0'
sac_steps_per_epoch: 4
sac_epochs: 12500
replay_size: 1000000
gamma: 0.95
polyak: 0.95
lr: 0.001
alpha: 0.2
batch_size: 1024
start_steps: 100
update_after: 100
update_every: 1
save_freq: 10
num_test_episodes: 10
log_dir: 'runs_rl/'
logging_dir: 'rl_training/logging/'
output_fname: 'my_progress.txt'
activation: 'ReLU'
hidden_sizes: [512, 512, 512]
whether_her: False
use_auto: True

pretrained: False
pretrained_itr: None
pretrained_fpath: None
