algo_name: 'sac_astar'
seed: 30
env_name: 'reaching-v0'
sac_steps_per_epoch: 2000
sac_epochs: 10000
replay_size: 1000000
gamma: 0.99
polyak: 0.95
lr: 0.001
alpha: 0.2
batch_size: 1024
start_steps: 1000
update_after: 1000
update_every: 2000
save_freq: 1000
num_test_episodes: 10
log_dir: 'runs_rl/'
logging_dir: 'runs_rl/'
output_fname: 'experiment_document.txt'
activation: 'ReLU'
hidden_sizes: [512, 512, 512]
whether_her: False
use_auto: True
whether_astar: False

pretrained: False
pretrained_itr: 3
pretrained_dir: 'runs_rl/reaching-v0_sac_astar_10_20240107_143228/'
