algo_name: 'sac_astar'
seed: 50
env_name: 'reaching-v0'
sac_steps_per_epoch: 50000
sac_epochs: 100
replay_size: 1000000
gamma: 0.95
polyak: 0.95
lr: 0.001
alpha: 0.2
batch_size: 1024
start_steps: 1000
update_after: 1000
update_every: 2000
save_freq: 1
num_test_episodes: 100
log_dir: 'runs_rl/'
logging_dir: 'runs_rl/'
output_fname: 'experiment_document.txt'
activation: 'ReLU'
hidden_sizes: [512, 512, 512]
whether_her: False
use_auto: True
whether_astar: True

pretrained: False
pretrained_itr: 2499999
pretrained_dir: 'runs_rl/reaching-v0_sac_astar_three_trailer_60_20240122_223222/'